name: scaffold_d
homepage: https://github.com/f1forhelp/generic_gen
repository: https://github.com/f1forhelp/generic_gen
issue_tracker: https://github.com/f1forhelp/generic_gen/issues
description: A feature-rich command-line interface (CLI) designed for Flutter applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3
 
# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  path: ^1.8.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
