name: scaffold_d
description: A sample command-line application with basic argument parsing.
homepage: https://www.example.com
repository: https://www.example.com
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3
 
# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  path: ^1.8.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
